In [1]:
import numpy as np
import pandas as pd

In [2]:
date_url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/orders.csv"

time_url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/messages.csv"

In [3]:
date = pd.read_csv(date_url)
time = pd.read_csv(time_url)

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Dates

In [8]:
date['date'] = pd.to_datetime(date['date'])

date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract Year

In [11]:
date['date_year'] = date['date'].dt.year

date.sample(8)

          date  product_id  city_id  orders  date_year
230 2018-07-22        7554       13      12       2018
694 2019-06-26         523       30       1       2019
648 2018-10-08         564       25       1       2018
81  2019-03-22        3143       25       1       2019
51  2019-08-12        6344       26       1       2019
86  2019-06-27        3904        1      29       2019
108 2019-10-24        7538        0       1       2019
348 2019-02-09        1848       14     135       2019

In [13]:
date['date_month'] = date['date'].dt.month

date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
156 2019-04-25         568        8      25       2019           4
712 2019-02-10        5290        3       8       2019           2
140 2018-10-31        5112       10       1       2018          10
927 2018-12-04         219        3       3       2018          12
724 2019-06-16        2415       22       1       2019           6

In [14]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [16]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [17]:
date['date_day_week'] = date['date'].dt.day_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_week
721,2019-06-13,1944,11,6,2019,6,June,13,Thursday
669,2018-10-31,1647,4,1,2018,10,October,31,Wednesday
30,2019-07-24,2820,16,4,2019,7,July,24,Wednesday
815,2019-12-08,3659,20,4,2019,12,December,8,Sunday
693,2019-07-26,2271,3,60,2019,7,July,26,Friday